language: node_js
node_js:
- stable
before_deploy:
  - cd functions 
  - pwd
  - npm install
  - cd ..
  - pwd
  - npm install
  - npm install eslint --save-dev
  - npm install lint
  - npm run lint
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN_RAW
